language: python

dist: xenial  # Ubuntu 16.04

env:
  - LC_ALL=C.UTF-8 LANG=C.UTF-8


# On trusty (or later) images, the Bazel apt repository can be used.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://bazel.build/bazel-release.pub.gpg'

services:
  - docker

before_install:
  - docker pull bitnami/mariadb:10.1.26-r0
  - docker run -dit -p 3306:3306 -e ALLOW_EMPTY_PASSWORD=yes --name mariadb bitnami/mariadb:10.1.26-r0
  - sleep 10

script:
  - ./bazelisk build //...
  - ./bazelisk test //... --test_output=errors
