package(default_visibility = ["//visibility:public"])

java_library(
    name = "mysql_driver",
    exports = [
        "@mysql_mysql_connector_java//jar",
    ]
)

java_library(
    name = "sqlite_driver",
    exports = [
        "@org_xerial_sqlite_jdbc//jar",
    ]
)
