workspace(name = "E02_mysql_database_config_json")

local_repository(
    name = "gpk_rules_datasource",
    path = "../..",
)

local_repository(
    name = "gpk_rules_pytest",
    path = "../../gpk_rules_pytest",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
        "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
    ],
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip",
    requirements_lock = "@gpk_rules_datasource//:requirements-lock.txt",
)

load("@pip//:requirements.bzl", "install_deps")

install_deps()

http_archive(
    name = "bazel_json",
    sha256 = "4860e929115395403f7b33fc32c2a034d4b7990364b65c22244cb58cadd3a4a5",
    strip_prefix = "bazel_json-e954ef2c28cd92d97304810e8999e1141e2b5cc8/lib",
    url = "https://github.com/erickj/bazel_json/archive/e954ef2c28cd92d97304810e8999e1141e2b5cc8.zip",
)

load("@gpk_rules_datasource//datasource:defs.bzl", "json_datasource_configuration")

json_datasource_configuration(
    name = "E02_datasources",
    config_file = "database.json",
    config_file_location = "@E02_mysql_database_config_json//:BUILD",
)

json_datasource_configuration(
    name = "E02_datasources_default",
    config_file = "database-non-existant.yml",
    config_file_location = "@E02_mysql_database_config_json//:BUILD",
    default_config = """
    {
        "mysql": {
            "host": "localhost",
            "port": 3306,
            "username": "root",
            "password": ""
        }
    }
    """,
)

rules_intellij_generate_sha = "f738a6306637b72a04ff80a0dfd9e70980bb08c1"

http_archive(
    name = "rules_intellij_generate",
    sha256 = "5fceea2c23cb9303e3eaeec5b3428a81ab4c243d8cb8e44ad971a6980f3bdaf9",
    strip_prefix = "rules_intellij_generate-%s/rules" % rules_intellij_generate_sha,
    url = "https://github.com/sconover/rules_intellij_generate/archive/%s.tar.gz" % rules_intellij_generate_sha,
)
