package(default_visibility = ["//visibility:public"])

alias(name="create_database_bin", actual="@copypastel_rules_datasource//pysrc:create_database")

test_suite(
    name = "tests",
    tests = [
        "//pytest:unit",
    ],
)
