workspace(name = "E01_mysql_database")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:pip.bzl", "pip_repositories", "pip_import")

pip_repositories()

local_repository(
    name = "copypastel_rules_datasource",
    path = "../../copypastel_rules_datasource",
)

local_repository(
    name = "gpk_rules_pytest",
    path = "../test",
)

pip_import(
    name = "pip",
    requirements = "@gpk_rules_pytest//:requirements.txt",
)

load("@pip//:requirements.bzl", "pip_install")

pip_install()

http_archive(
    name = "bazel_json",
    sha256 = "4860e929115395403f7b33fc32c2a034d4b7990364b65c22244cb58cadd3a4a5",
    strip_prefix = "bazel_json-e954ef2c28cd92d97304810e8999e1141e2b5cc8/lib",
    url = "https://github.com/erickj/bazel_json/archive/e954ef2c28cd92d97304810e8999e1141e2b5cc8.zip",
)
