test_suite(
    name = "tests",
    tests = [
        "@E01_mysql_database//:suite",
        "@E02_mysql_database_config_json//:suite",
        # "@E03_mysql_flyway_migration//:suite",
    ],
    visibility = ["//visibility:public"],
)
