workspace(name = "E04_mysql_flyway_migration_workspace")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "gpk_rules_datasource",
    path = "../..",
)

local_repository(
    name = "gpk_rules_pytest",
    path = "../../gpk_rules_pytest",
)

http_archive(
    name = "rules_python",
    sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
        "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
    ],
)

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "pip",
    requirements_lock = "@gpk_rules_datasource//:requirements-lock.txt",
)

load("@pip//:requirements.bzl", "install_deps")

install_deps()

http_archive(
    name = "bazel_json",
    sha256 = "4860e929115395403f7b33fc32c2a034d4b7990364b65c22244cb58cadd3a4a5",
    strip_prefix = "bazel_json-e954ef2c28cd92d97304810e8999e1141e2b5cc8/lib",
    url = "https://github.com/erickj/bazel_json/archive/e954ef2c28cd92d97304810e8999e1141e2b5cc8.zip",
)

rules_intellij_generate_sha = "f738a6306637b72a04ff80a0dfd9e70980bb08c1"

http_archive(
    name = "rules_intellij_generate",
    sha256 = "5fceea2c23cb9303e3eaeec5b3428a81ab4c243d8cb8e44ad971a6980f3bdaf9",
    strip_prefix = "rules_intellij_generate-%s/rules" % rules_intellij_generate_sha,
    url = "https://github.com/sconover/rules_intellij_generate/archive/%s.tar.gz" % rules_intellij_generate_sha,
)

### 04 example tests workspace rules
load("@gpk_rules_datasource//datasource:defs.bzl", "local_datasource_configuration")

local_datasource_configuration(
    name = "E04_mysql",
    host = "localhost",
    jdbc_connection_string = "jdbc:mysql://localhost:3306?serverTimezone=UTC",
    jdbc_connector = "@maven//:mysql_mysql_connector_java",
    password = "",
    port = "3306",
    username = "root",
)

load("@gpk_rules_datasource//flyway:defs.bzl", "local_database")

local_database(
    name = "E04db",
    datasource_configuration = "@E04_mysql",
    dbname = "04_mysql_flyway_migration_workspace",
    migrations = ["@E04_mysql_flyway_migration_workspace//:migrations"],
    recalculate_when = ["//:.bazelexec.stamp"],
)

### Flyway
RULES_JVM_EXTERNAL_TAG = "3.2"

RULES_JVM_EXTERNAL_SHA = "82262ff4223c5fda6fb7ff8bd63db8131b51b413d26eb49e3131037e79e324af"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

# to update the json file, see https://github.com/bazelbuild/rules_jvm_external#updating-maven_installjson
maven_install(
    name = "maven",
    artifacts = [
        "org.flywaydb:flyway-commandline:6.4.2",
        "mysql:mysql-connector-java:8.0.20",
    ],
    maven_install_json = "@gpk_rules_datasource//:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
    version_conflict_policy = "pinned",
)

load("@maven//:defs.bzl", "pinned_maven_install")

pinned_maven_install()
